#!/bin/bash

# Triggered during the finalization of a desktop session (KDE/gnome):
#
# Category:
# - onEveryTime: runs scripts everytime a desktop session ends
#
# Host type:
# defined as a child of the category, it tells the type of host it should
# be executed. This is done by reading the env var $BSYS_HOST_TYPE. In case a script
# is meant to be executed in any host then place it under "all" (rather then duplicating it
# accross all hosts...)
#
# Script conventions:
# - make sure the scripts have the shebang (#!) and are set as executable.
# - a script named as "main" is executed first than the other scritps

# current directory
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# sourcing function used for the execution of the scripts
source "$dir/aux/execScripts"

# executing scripts
categories="onEveryTime"
for category in $categories ; do
  allScriptPath="$BEVENTS_CONFIG_ROOT/events/desktop-end/$category/all/$BSYS_OS/$BSYS_OS_VERSION"
  hostTypeScriptPath="$BEVENTS_CONFIG_ROOT/events/desktop-end/$category/$BSYS_HOST_TYPE/$BSYS_OS/$BSYS_OS_VERSION"

  execScripts "$allScriptPath" "$hostTypeScriptPath"
done
